apiVersion: apps/v1
kind: Deployment
metadata:
  name: invariant-mass-analysis
  labels:
    app: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: transform-cli
        image: sslhep/servicex-analysis:latest
        imagePullPolicy: Always
