apiVersion: v1
kind: Pod
metadata:
  name: invariant-mass-analysis
spec:
  containers:
  - name: transform-cli
    image: sslhep/servicex-analysis:latest
    imagePullPolicy: Always
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
