apiVersion: batch/v1
kind: Job
metadata:
  name: invariant-mass-job
spec:
  backoffLimit: 6 # number of retries before throwing error
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      restartPolicy: Never
      containers:
      - name: invariant-mass
        image: sslhep/servicex-analysis:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - "python /servicex/invariant_mass.py --broker servicex-kafka.kafka.svc.cluster.local"
